### ISSUE TITLE
Unavailable for legal reasons

### ISSUE THREAD

**Issue by dsx** [Tracker-CLI/covid19-tracker-cli#41]
What happened?

```
> curl -s -L covid19.trackercli.com/ca
Unavailable for legal reasons

DEPLOYMENT_BLOCKED

```

**Comment by jkga** [comment]
Thank you @dsx  for reporting. **temporarily** you can use the domain  below while we are inspecting the issue.
> curl curl https://covid19-tracker-cli.now.sh/ca

**Comment by WarenGonzaga** [comment]
@dsx please join our discord server for more updates: discord.gg/6Gzxwtt

We are working for a fix... thank you!

**Comment by WarenGonzaga** [comment]
@dsx issue fixed...
